# Generated by Django 4.1.6 on 2023-04-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_img_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_link',
            field=models.URLField(default=None),
        ),
    ]
