# Generated by Django 4.1.6 on 2023-04-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_link',
            field=models.URLField(default=''),
        ),
    ]
