# Generated by Django 4.1.6 on 2023-04-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_url_news_complete_new_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='complete_new_url',
            field=models.URLField(default=''),
        ),
    ]
